source 'https://rubygems.org'

gem 'travis-config',      '~> 1.0.6'
gem 'travis-metrics',     '~> 2.0.0.rc3'
gem 'travis-lock'
gem 'travis-rollout'
gem 'travis-exceptions',  github: 'travis-ci/travis-exceptions'
gem 'travis-logger',      github: 'travis-ci/travis-logger'
gem 'travis-settings',    github: 'travis-ci/travis-settings'
gem 'gh',                 github: 'travis-ci/gh'
gem 'coder',              github: 'rkh/coder'

gem 'sidekiq-pro', require: 'sidekiq-pro', source: 'https://gems.contribsys.com'
gem 'jemalloc'
gem 'redis-namespace'
gem 'activerecord'
gem 'bunny'
gem 'pg'
gem 'concurrent-ruby'
gem 'sentry-raven'
gem 'rollout'
gem 'redlock'
gem 'multi_json',         '~> 1.11'
gem 'rack', '1.6.4'

group :test do
  gem 'rake'
  gem 'database_cleaner', '~> 1.5.1'
  gem 'factory_girl'
  gem 'mocha',            '~> 0.10.0'
  gem 'rspec'
  gem 'webmock',          '~> 1.8.0'
end
